### ISSUE TITLE
Minor bug 2:-)

### ISSUE THREAD

**Issue by perhedeland** [grembo/xorg-udev-setup-check#2]
Also wasn't triggered when I ran the script since I already had i915kms loaded:

\---------------------------------------------
Neither i915kms nor radeonkms is loaded.
Please load using

kldload i915kms
or
kldload radeonkms

You can load one of these drivers automatically on
boot by adding it to kld_list in rc.conf:

sysrc kld_list+=/boot/modules/i915kms.ko
or
sysrc kld_list+=/boot/modules/radeonkms.ko
\---------------------------------------------

Those kldload commands do *not* do the same thing as the kld_list additions, at least with the default  kern.module_path:

kern.module_path: /boot/kernel;/boot/modules;/boot/dtb;/boot/dtb/overlays

I.e. the kldload commands will actually load the **non**-"new drm" versions of the modules from /boot/kernel (at least in 12.1-STABLE, they're still there) - I assume this isn't the intent. I.e. they also need the /boot/modules/ prefix.

**Comment by grembo** [comment]
Eagle eyes, thank you :)

Also, kld_list shouldn’t need .ko file extensions, will address that in another commit.

**Comment by perhedeland** [comment]
Well, doesn't hurt:-) - here's mine, inconsistent and all:

kld_list="/boot/modules/i915kms.ko iichid"

**Comment by grembo** [comment]
> Well, doesn't hurt:-) - here's mine, inconsistent and all:
> 
> kld_list="/boot/modules/i915kms.ko iichid"

Actually, .ko *is* required when loading from a path. In general, I think it makes sense,
it's just that the man page isn't very explicit about it (but the examples show
that it's intentional). 

Interestingly, if the module is already loaded, it appears to work:

    kldload /boot/modules/i915kms
    kldload: can't load /boot/modules/i915kms: module already loaded or in kernel

If it isn't, it fails

    kldload /boot/modules/i915kms
    kldload: can't load /boot/modules/i915kms: No such file or directory

So file existence is only checked if the module name isn't already known to the
kernel.

Good news is that checking if a module is loaded by `kldstat -m i915kms`/`kldstat -m radeonkms` is sufficient, as the versions that ship with base contain modules of different names (_vgapci/i915kms_ and _vgapci/radeonkms_) that won't show up in that check, even if loaded.

**Comment by perhedeland** [comment]
On 2020-02-26 02:59, grembo wrote:
>
> Good news is that checking if a module is loaded by |kldstat -m i915kms|/|kldstat -m radeonkms| is sufficient, as the versions that ship with base contain modules of different names (/vgapci/i915kms/
> and /vgapci/radeonkms/) that won't show up in that check, even if loaded.

Actually 'kldstat -v' works too since it shows the path, might be
simpler.

**Comment by grembo** [comment]
I had that implemented already (kldstat -v and verify path), but when I realized that the existing

  kldstat -m i915kms

logic does the right thing, I decided to remove that again, as the logic was more complicated than this one line above.
